// ============================================================
// EMPATHETIC AI CHAT APP — Flutter + Hive
// ============================================================
// 
// Setup Instructions:
// 1. Add dependencies to pubspec.yaml:
//
// dependencies:
//   flutter:
//     sdk: flutter
//   hive: ^2.2.3
//   hive_flutter: ^1.1.0
//   path_provider: ^2.1.2
//   uuid: ^4.3.3
//   intl: ^0.19.0
//   google_fonts: ^6.1.0
//
// dev_dependencies:
//   hive_generator: ^2.0.1
//   build_runner: ^2.4.8
//
// 2. Run: flutter pub get
// 3. Run: dart run build_runner build
// 4. Place all files in lib/ folder
// ============================================================

// ─────────────────────────────────────────────────────────────
// FILE: lib/main.dart
// ─────────────────────────────────────────────────────────────
/*
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/message_model.dart';
import 'models/conversation_model.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter();

  // Register adapters
  Hive.registerAdapter(MessageModelAdapter());
  Hive.registerAdapter(ConversationModelAdapter());

  // Open boxes
  await Hive.openBox<ConversationModel>('conversations');
  await Hive.openBox<MessageModel>('messages');

  runApp(const EmpathApp());
}

class EmpathApp extends StatelessWidget {
  const EmpathApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Empath AI',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      home: const HomeScreen(),
    );
  }
}
*/

// ─────────────────────────────────────────────────────────────
// COMPLETE SINGLE-FILE IMPLEMENTATION
// Save as: lib/main.dart
// ─────────────────────────────────────────────────────────────

// ignore_for_file: depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:uuid/uuid.dart';
import 'package:intl/intl.dart';
import 'package:google_fonts/google_fonts.dart';
import 'dart:async';
import 'dart:math';

// ─────────────────────────────────────────────────────────────
// HIVE MODELS
// ─────────────────────────────────────────────────────────────

part 'main.g.dart';  // Generated by build_runner

@HiveType(typeId: 0)
class MessageModel extends HiveObject {
  @HiveField(0)
  late String id;

  @HiveField(1)
  late String conversationId;

  @HiveField(2)
  late String content;

  @HiveField(3)
  late bool isUser;

  @HiveField(4)
  late DateTime timestamp;

  @HiveField(5)
  late String emotion;

  @HiveField(6)
  late double emotionConfidence;

  MessageModel({
    required this.id,
    required this.conversationId,
    required this.content,
    required this.isUser,
    required this.timestamp,
    required this.emotion,
    required this.emotionConfidence,
  });
}

@HiveType(typeId: 1)
class ConversationModel extends HiveObject {
  @HiveField(0)
  late String id;

  @HiveField(1)
  late String title;

  @HiveField(2)
  late DateTime createdAt;

  @HiveField(3)
  late DateTime updatedAt;

  @HiveField(4)
  late String lastMessage;

  @HiveField(5)
  late String dominantEmotion;

  ConversationModel({
    required this.id,
    required this.title,
    required this.createdAt,
    required this.updatedAt,
    required this.lastMessage,
    required this.dominantEmotion,
  });
}

// ─────────────────────────────────────────────────────────────
// EMOTION DETECTOR (keyword-based, mirrors Python logic)
// ─────────────────────────────────────────────────────────────

class EmotionDetector {
  static const Map<String, List<String>> _keywords = {
    'joy': ['happy', 'excited', 'great', 'amazing', 'wonderful', 'thrilled',
            'proud', 'love', 'fantastic', 'excellent', 'promoted', 'celebrate'],
    'sadness': ['sad', 'depress', 'cry', 'lonely', 'hopeless', 'grief',
                'loss', 'empty', 'numb', 'worthless', 'miss', 'alone', 'hurt'],
    'anger': ['angry', 'anger', 'furious', 'rage', 'frustrated', 'irritated',
              'annoyed', 'mad', 'upset', 'blame', 'unfair', 'hate'],
    'fear': ['scared', 'afraid', 'anxious', 'anxiety', 'fear', 'terror',
             'panic', 'worry', 'overwhelm', 'stress', 'nervous', 'terrified'],
    'disgust': ['disgust', 'sick', 'gross', 'repuls', 'awful', 'horrible'],
    'surprise': ['surprise', 'shock', 'unexpected', 'sudden', 'unbelievable',
                 'wow', 'omg', 'cant believe'],
  };

  static MapEntry<String, double> detect(String text) {
    final lower = text.toLowerCase();
    final scores = <String, int>{};

    for (final entry in _keywords.entries) {
      int count = 0;
      for (final kw in entry.value) {
        if (lower.contains(kw)) count++;
      }
      if (count > 0) scores[entry.key] = count;
    }

    if (scores.isEmpty) return const MapEntry('neutral', 0.5);

    final best = scores.entries.reduce((a, b) => a.value > b.value ? a : b);
    final confidence = (0.6 + (best.value * 0.1)).clamp(0.6, 0.95);
    return MapEntry(best.key, confidence);
  }

  static Color getEmotionColor(String emotion) {
    return switch (emotion) {
      'joy'      => const Color(0xFFFFD700),
      'sadness'  => const Color(0xFF6495ED),
      'anger'    => const Color(0xFFFF4444),
      'fear'     => const Color(0xFFAA44FF),
      'disgust'  => const Color(0xFF44AA44),
      'surprise' => const Color(0xFFFF8C00),
      _          => const Color(0xFF888888),
    };
  }

  static String getEmotionEmoji(String emotion) {
    return switch (emotion) {
      'joy'      => '😊',
      'sadness'  => '💙',
      'anger'    => '😤',
      'fear'     => '😰',
      'disgust'  => '😣',
      'surprise' => '😮',
      _          => '😐',
    };
  }
}

// ─────────────────────────────────────────────────────────────
// MOCK AI RESPONSES (mirrors trained model behavior)
// ─────────────────────────────────────────────────────────────

class MockAIService {
  static final _random = Random();

  static const Map<String, List<String>> _responses = {
    'joy': [
      "That's truly wonderful news! You must be feeling so proud of yourself right now. What's been the most rewarding part of this achievement for you?",
      "How exciting! It sounds like your hard work is really paying off. How are you planning to celebrate this moment?",
      "That's such great news to hear! You deserve to feel happy about this. What does this mean for you going forward?",
    ],
    'sadness': [
      "I'm really sorry you're going through this. Feeling lonely can be incredibly difficult. Would you like to talk about what's been making you feel this way?",
      "It sounds like you're carrying a lot right now. That kind of pain deserves acknowledgment. What's been weighing on you the most?",
      "I hear you, and I want you to know that what you're feeling is completely valid. Is there something specific that's been on your mind lately?",
    ],
    'anger': [
      "That sounds really frustrating. Being treated unfairly is one of the hardest things to deal with. How are you handling the situation right now?",
      "I completely understand why you'd feel that way. It's natural to feel upset when things aren't fair. What do you think would help resolve this?",
      "Your feelings make total sense given the situation. Sometimes things just aren't right and it's okay to be upset about that. What would help you feel better?",
    ],
    'fear': [
      "It's completely natural to feel anxious about something important. Taking things one step at a time can really help. What feels most overwhelming right now?",
      "That kind of nervousness shows how much you care. Let's think through this together — what's the part that worries you most?",
      "Feeling scared before something big is very normal. Your feelings are valid. What would make you feel a little more prepared?",
    ],
    'disgust': [
      "That does sound really unpleasant. It's understandable to feel that way. How has this been affecting you?",
      "I can understand why that would bother you so much. Some things are genuinely hard to accept. What do you think should be done about it?",
    ],
    'surprise': [
      "Wow, that must have caught you completely off guard! How are you feeling about it now that it's happened?",
      "That's quite unexpected! Sometimes life throws us these little curveballs. How are you processing this?",
      "What a surprising turn of events! How does that make you feel?",
    ],
    'neutral': [
      "I'm here to listen. Tell me more about what's on your mind.",
      "That's interesting — I'd love to hear more about that. How are you feeling about things overall?",
      "Thanks for sharing that with me. How has your day been going?",
      "I appreciate you talking with me. What's been on your mind lately?",
    ],
  };

  static Future<String> getResponse(String userMessage, String emotion) async {
    // Simulate network delay like real model inference
    await Future.delayed(Duration(milliseconds: 800 + _random.nextInt(1200)));

    final responses = _responses[emotion] ?? _responses['neutral']!;
    return responses[_random.nextInt(responses.length)];
  }
}

// ─────────────────────────────────────────────────────────────
// HIVE SERVICE
// ─────────────────────────────────────────────────────────────

class HiveService {
  static const String _conversationsBox = 'conversations';
  static const String _messagesBox = 'messages';
  static final _uuid = const Uuid();

  static Box<ConversationModel> get _conversations =>
      Hive.box<ConversationModel>(_conversationsBox);

  static Box<MessageModel> get _messages =>
      Hive.box<MessageModel>(_messagesBox);

  // ── Conversations ──────────────────────────────────────────

  static Future<ConversationModel> createConversation(String firstMessage) async {
    final id = _uuid.v4();
    final now = DateTime.now();
    final conv = ConversationModel(
      id: id,
      title: firstMessage.length > 40
          ? '${firstMessage.substring(0, 40)}...'
          : firstMessage,
      createdAt: now,
      updatedAt: now,
      lastMessage: firstMessage,
      dominantEmotion: 'neutral',
    );
    await _conversations.put(id, conv);
    return conv;
  }

  static List<ConversationModel> getAllConversations() {
    final list = _conversations.values.toList();
    list.sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
    return list;
  }

  static Future<void> updateConversation(
      String id, String lastMessage, String emotion) async {
    final conv = _conversations.get(id);
    if (conv != null) {
      conv.lastMessage = lastMessage;
      conv.updatedAt = DateTime.now();
      conv.dominantEmotion = emotion;
      await conv.save();
    }
  }

  static Future<void> deleteConversation(String id) async {
    // Delete all messages in this conversation
    final toDelete = _messages.values
        .where((m) => m.conversationId == id)
        .map((m) => m.id)
        .toList();
    for (final msgId in toDelete) {
      await _messages.delete(msgId);
    }
    await _conversations.delete(id);
  }

  // ── Messages ───────────────────────────────────────────────

  static Future<MessageModel> saveMessage({
    required String conversationId,
    required String content,
    required bool isUser,
    required String emotion,
    required double emotionConfidence,
  }) async {
    final id = _uuid.v4();
    final msg = MessageModel(
      id: id,
      conversationId: conversationId,
      content: content,
      isUser: isUser,
      timestamp: DateTime.now(),
      emotion: emotion,
      emotionConfidence: emotionConfidence,
    );
    await _messages.put(id, msg);
    return msg;
  }

  static List<MessageModel> getMessagesForConversation(String conversationId) {
    final list = _messages.values
        .where((m) => m.conversationId == conversationId)
        .toList();
    list.sort((a, b) => a.timestamp.compareTo(b.timestamp));
    return list;
  }

  static int getTotalMessageCount() => _messages.length;
  static int getTotalConversationCount() => _conversations.length;
}

// ─────────────────────────────────────────────────────────────
// THEME
// ─────────────────────────────────────────────────────────────

class AppTheme {
  // Deep teal-midnight palette — warm, trustworthy, clinical-free
  static const Color background   = Color(0xFF0D1117);
  static const Color surface      = Color(0xFF161B22);
  static const Color surfaceLight = Color(0xFF21262D);
  static const Color accent       = Color(0xFF58A6FF);
  static const Color accentWarm   = Color(0xFFE3A46A);
  static const Color textPrimary  = Color(0xFFE6EDF3);
  static const Color textSecondary= Color(0xFF8B949E);
  static const Color userBubble   = Color(0xFF1F6FEB);
  static const Color aiBubble     = Color(0xFF21262D);
  static const Color divider      = Color(0xFF30363D);

  static ThemeData get darkTheme => ThemeData(
    brightness: Brightness.dark,
    scaffoldBackgroundColor: background,
    colorScheme: const ColorScheme.dark(
      primary: accent,
      secondary: accentWarm,
      surface: surface,
      background: background,
    ),
    textTheme: GoogleFonts.dmSansTextTheme(
      ThemeData.dark().textTheme,
    ).apply(
      bodyColor: textPrimary,
      displayColor: textPrimary,
    ),
    appBarTheme: AppBarTheme(
      backgroundColor: surface,
      elevation: 0,
      centerTitle: false,
      titleTextStyle: GoogleFonts.dmSans(
        color: textPrimary,
        fontSize: 18,
        fontWeight: FontWeight.w600,
      ),
      iconTheme: const IconThemeData(color: textSecondary),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: surfaceLight,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(24),
        borderSide: BorderSide.none,
      ),
      hintStyle: GoogleFonts.dmSans(color: textSecondary, fontSize: 15),
      contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
    ),
  );
}

// ─────────────────────────────────────────────────────────────
// MAIN ENTRY POINT
// ─────────────────────────────────────────────────────────────

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
  ));

  await Hive.initFlutter();
  Hive.registerAdapter(MessageModelAdapter());
  Hive.registerAdapter(ConversationModelAdapter());
  await Hive.openBox<ConversationModel>('conversations');
  await Hive.openBox<MessageModel>('messages');

  runApp(const EmpathApp());
}

class EmpathApp extends StatelessWidget {
  const EmpathApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Empath AI',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      home: const HomeScreen(),
    );
  }
}

// ─────────────────────────────────────────────────────────────
// HOME SCREEN — Conversation List
// ─────────────────────────────────────────────────────────────

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen>
    with SingleTickerProviderStateMixin {
  List<ConversationModel> _conversations = [];
  late AnimationController _fabController;

  @override
  void initState() {
    super.initState();
    _fabController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 300),
    );
    _loadConversations();
    _fabController.forward();
  }

  @override
  void dispose() {
    _fabController.dispose();
    super.dispose();
  }

  void _loadConversations() {
    setState(() {
      _conversations = HiveService.getAllConversations();
    });
  }

  Future<void> _startNewConversation() async {
    final conv = await HiveService.createConversation('New conversation');
    if (!mounted) return;
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ChatScreen(conversation: conv),
      ),
    );
    _loadConversations();
  }

  Future<void> _openConversation(ConversationModel conv) async {
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ChatScreen(conversation: conv),
      ),
    );
    _loadConversations();
  }

  Future<void> _deleteConversation(ConversationModel conv) async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surface,
        title: Text('Delete conversation',
            style: GoogleFonts.dmSans(color: AppTheme.textPrimary)),
        content: Text('This conversation will be permanently deleted.',
            style: GoogleFonts.dmSans(color: AppTheme.textSecondary)),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: Text('Cancel',
                style: GoogleFonts.dmSans(color: AppTheme.textSecondary)),
          ),
          TextButton(
            onPressed: () => Navigator.pop(ctx, true),
            child: Text('Delete',
                style: GoogleFonts.dmSans(color: Colors.redAccent)),
          ),
        ],
      ),
    );
    if (confirm == true) {
      await HiveService.deleteConversation(conv.id);
      _loadConversations();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      appBar: AppBar(
        title: Row(
          children: [
            Container(
              width: 32,
              height: 32,
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [AppTheme.accent, AppTheme.accentWarm],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(8),
              ),
              child: const Icon(Icons.favorite_rounded,
                  color: Colors.white, size: 18),
            ),
            const SizedBox(width: 10),
            Text('Empath AI',
                style: GoogleFonts.dmSans(
                  color: AppTheme.textPrimary,
                  fontWeight: FontWeight.w700,
                  fontSize: 20,
                )),
          ],
        ),
        actions: [
          _StatsChip(
            count: HiveService.getTotalConversationCount(),
            label: 'chats',
          ),
          const SizedBox(width: 12),
        ],
      ),
      body: _conversations.isEmpty
          ? _buildEmptyState()
          : _buildConversationList(),
      floatingActionButton: ScaleTransition(
        scale: CurvedAnimation(
          parent: _fabController,
          curve: Curves.elasticOut,
        ),
        child: FloatingActionButton.extended(
          onPressed: _startNewConversation,
          backgroundColor: AppTheme.accent,
          icon: const Icon(Icons.add_comment_rounded, color: Colors.white),
          label: Text('New Chat',
              style: GoogleFonts.dmSans(
                color: Colors.white,
                fontWeight: FontWeight.w600,
              )),
        ),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              color: AppTheme.surfaceLight,
              borderRadius: BorderRadius.circular(20),
            ),
            child: const Icon(Icons.chat_bubble_outline_rounded,
                color: AppTheme.textSecondary, size: 36),
          ),
          const SizedBox(height: 20),
          Text('No conversations yet',
              style: GoogleFonts.dmSans(
                color: AppTheme.textPrimary,
                fontSize: 20,
                fontWeight: FontWeight.w600,
              )),
          const SizedBox(height: 8),
          Text('Start a new chat to talk with\nyour empathetic AI companion',
              textAlign: TextAlign.center,
              style: GoogleFonts.dmSans(
                color: AppTheme.textSecondary,
                fontSize: 14,
                height: 1.5,
              )),
          const SizedBox(height: 32),
          ElevatedButton.icon(
            onPressed: _startNewConversation,
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.accent,
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12)),
            ),
            icon: const Icon(Icons.add_rounded, color: Colors.white),
            label: Text('Start Chatting',
                style: GoogleFonts.dmSans(
                  color: Colors.white,
                  fontWeight: FontWeight.w600,
                  fontSize: 15,
                )),
          ),
        ],
      ),
    );
  }

  Widget _buildConversationList() {
    return ListView.separated(
      padding: const EdgeInsets.fromLTRB(16, 12, 16, 100),
      itemCount: _conversations.length,
      separatorBuilder: (_, __) => const SizedBox(height: 8),
      itemBuilder: (context, index) {
        final conv = _conversations[index];
        return _ConversationTile(
          conversation: conv,
          onTap: () => _openConversation(conv),
          onDelete: () => _deleteConversation(conv),
        );
      },
    );
  }
}

// ─────────────────────────────────────────────────────────────
// CONVERSATION TILE
// ─────────────────────────────────────────────────────────────

class _ConversationTile extends StatelessWidget {
  final ConversationModel conversation;
  final VoidCallback onTap;
  final VoidCallback onDelete;

  const _ConversationTile({
    required this.conversation,
    required this.onTap,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final emotionColor =
        EmotionDetector.getEmotionColor(conversation.dominantEmotion);
    final emoji =
        EmotionDetector.getEmotionEmoji(conversation.dominantEmotion);
    final timeStr = _formatTime(conversation.updatedAt);

    return Dismissible(
      key: Key(conversation.id),
      direction: DismissDirection.endToStart,
      background: Container(
        alignment: Alignment.centerRight,
        padding: const EdgeInsets.only(right: 20),
        decoration: BoxDecoration(
          color: Colors.redAccent.withOpacity(0.2),
          borderRadius: BorderRadius.circular(16),
        ),
        child: const Icon(Icons.delete_rounded, color: Colors.redAccent),
      ),
      onDismissed: (_) => onDelete(),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(16),
          child: Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppTheme.surface,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(
                color: AppTheme.divider,
                width: 1,
              ),
            ),
            child: Row(
              children: [
                // Emotion avatar
                Container(
                  width: 48,
                  height: 48,
                  decoration: BoxDecoration(
                    color: emotionColor.withOpacity(0.15),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: emotionColor.withOpacity(0.3),
                      width: 1,
                    ),
                  ),
                  child: Center(
                    child: Text(emoji, style: const TextStyle(fontSize: 22)),
                  ),
                ),
                const SizedBox(width: 14),
                // Content
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Expanded(
                            child: Text(
                              conversation.title,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                              style: GoogleFonts.dmSans(
                                color: AppTheme.textPrimary,
                                fontWeight: FontWeight.w600,
                                fontSize: 14,
                              ),
                            ),
                          ),
                          Text(
                            timeStr,
                            style: GoogleFonts.dmSans(
                              color: AppTheme.textSecondary,
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 4),
                      Text(
                        conversation.lastMessage,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: GoogleFonts.dmSans(
                          color: AppTheme.textSecondary,
                          fontSize: 13,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 8),
                const Icon(Icons.chevron_right_rounded,
                    color: AppTheme.textSecondary, size: 20),
              ],
            ),
          ),
        ),
      ),
    );
  }

  String _formatTime(DateTime dt) {
    final now = DateTime.now();
    final diff = now.difference(dt);
    if (diff.inMinutes < 1) return 'Just now';
    if (diff.inHours < 1) return '${diff.inMinutes}m ago';
    if (diff.inDays < 1) return DateFormat('HH:mm').format(dt);
    if (diff.inDays < 7) return DateFormat('EEE').format(dt);
    return DateFormat('MMM d').format(dt);
  }
}

// ─────────────────────────────────────────────────────────────
// CHAT SCREEN
// ─────────────────────────────────────────────────────────────

class ChatScreen extends StatefulWidget {
  final ConversationModel conversation;

  const ChatScreen({super.key, required this.conversation});

  @override
  State<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen>
    with SingleTickerProviderStateMixin {
  final TextEditingController _controller = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  final FocusNode _focusNode = FocusNode();

  List<MessageModel> _messages = [];
  bool _isTyping = false;
  String _currentEmotion = 'neutral';
  double _currentConfidence = 0.5;

  late AnimationController _typingController;
  late Animation<double> _typingAnimation;

  @override
  void initState() {
    super.initState();
    _typingController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1000),
    )..repeat(reverse: true);
    _typingAnimation = Tween<double>(begin: 0.4, end: 1.0)
        .animate(_typingController);
    _loadMessages();
  }

  @override
  void dispose() {
    _controller.dispose();
    _scrollController.dispose();
    _focusNode.dispose();
    _typingController.dispose();
    super.dispose();
  }

  void _loadMessages() {
    setState(() {
      _messages =
          HiveService.getMessagesForConversation(widget.conversation.id);
    });
    _scrollToBottom();
  }

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  Future<void> _sendMessage() async {
    final text = _controller.text.trim();
    if (text.isEmpty || _isTyping) return;

    _controller.clear();

    // Detect emotion
    final emotionResult = EmotionDetector.detect(text);
    _currentEmotion = emotionResult.key;
    _currentConfidence = emotionResult.value;

    // Save user message
    final userMsg = await HiveService.saveMessage(
      conversationId: widget.conversation.id,
      content: text,
      isUser: true,
      emotion: _currentEmotion,
      emotionConfidence: _currentConfidence,
    );

    setState(() {
      _messages.add(userMsg);
      _isTyping = true;
    });
    _scrollToBottom();

    // Update conversation
    await HiveService.updateConversation(
        widget.conversation.id, text, _currentEmotion);

    // Get AI response
    final response =
        await MockAIService.getResponse(text, _currentEmotion);

    // Save AI message
    final aiMsg = await HiveService.saveMessage(
      conversationId: widget.conversation.id,
      content: response,
      isUser: false,
      emotion: _currentEmotion,
      emotionConfidence: _currentConfidence,
    );

    await HiveService.updateConversation(
        widget.conversation.id, response, _currentEmotion);

    setState(() {
      _messages.add(aiMsg);
      _isTyping = false;
    });
    _scrollToBottom();
  }

  @override
  Widget build(BuildContext context) {
    final emotionColor = EmotionDetector.getEmotionColor(_currentEmotion);

    return Scaffold(
      backgroundColor: AppTheme.background,
      appBar: AppBar(
        backgroundColor: AppTheme.surface,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded,
              color: AppTheme.textSecondary),
          onPressed: () => Navigator.pop(context),
        ),
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Empath AI',
              style: GoogleFonts.dmSans(
                color: AppTheme.textPrimary,
                fontWeight: FontWeight.w600,
                fontSize: 16,
              ),
            ),
            Row(
              children: [
                Container(
                  width: 8,
                  height: 8,
                  decoration: const BoxDecoration(
                    color: Color(0xFF3FB950),
                    shape: BoxShape.circle,
                  ),
                ),
                const SizedBox(width: 6),
                Text(
                  'Online',
                  style: GoogleFonts.dmSans(
                    color: AppTheme.textSecondary,
                    fontSize: 12,
                  ),
                ),
              ],
            ),
          ],
        ),
        actions: [
          if (_currentEmotion != 'neutral')
            _EmotionBadge(
              emotion: _currentEmotion,
              confidence: _currentConfidence,
            ),
          const SizedBox(width: 12),
        ],
      ),
      body: Column(
        children: [
          // Emotion indicator bar
          AnimatedContainer(
            duration: const Duration(milliseconds: 500),
            height: 3,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  emotionColor.withOpacity(0.0),
                  emotionColor.withOpacity(0.8),
                  emotionColor.withOpacity(0.0),
                ],
              ),
            ),
          ),

          // Messages list
          Expanded(
            child: _messages.isEmpty
                ? _buildWelcomeMessage()
                : ListView.builder(
                    controller: _scrollController,
                    padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
                    itemCount: _messages.length + (_isTyping ? 1 : 0),
                    itemBuilder: (context, index) {
                      if (index == _messages.length && _isTyping) {
                        return _TypingIndicator(
                            animation: _typingAnimation);
                      }
                      return _MessageBubble(message: _messages[index]);
                    },
                  ),
          ),

          // Input area
          _buildInputArea(),
        ],
      ),
    );
  }

  Widget _buildWelcomeMessage() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 72,
              height: 72,
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [AppTheme.accent, AppTheme.accentWarm],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(20),
              ),
              child: const Icon(Icons.favorite_rounded,
                  color: Colors.white, size: 32),
            ),
            const SizedBox(height: 20),
            Text(
              'Hi, I\'m here for you',
              style: GoogleFonts.dmSans(
                color: AppTheme.textPrimary,
                fontSize: 22,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 10),
            Text(
              'Share what\'s on your mind.\nI\'ll listen with care and empathy.',
              textAlign: TextAlign.center,
              style: GoogleFonts.dmSans(
                color: AppTheme.textSecondary,
                fontSize: 14,
                height: 1.6,
              ),
            ),
            const SizedBox(height: 32),
            // Suggestion chips
            Wrap(
              spacing: 8,
              runSpacing: 8,
              alignment: WrapAlignment.center,
              children: [
                "I'm feeling anxious",
                "I had a great day!",
                "I need to talk",
                "I'm feeling lonely",
              ].map((suggestion) => _SuggestionChip(
                    text: suggestion,
                    onTap: () {
                      _controller.text = suggestion;
                      _sendMessage();
                    },
                  )).toList(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildInputArea() {
    return Container(
      padding: EdgeInsets.fromLTRB(
          16, 12, 16, MediaQuery.of(context).padding.bottom + 12),
      decoration: BoxDecoration(
        color: AppTheme.surface,
        border: const Border(
          top: BorderSide(color: AppTheme.divider, width: 1),
        ),
      ),
      child: Row(
        children: [
          Expanded(
            child: TextField(
              controller: _controller,
              focusNode: _focusNode,
              style: GoogleFonts.dmSans(
                color: AppTheme.textPrimary,
                fontSize: 15,
              ),
              maxLines: 4,
              minLines: 1,
              textCapitalization: TextCapitalization.sentences,
              decoration: InputDecoration(
                hintText: 'Share how you\'re feeling...',
                filled: true,
                fillColor: AppTheme.surfaceLight,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(20),
                  borderSide: BorderSide.none,
                ),
                contentPadding: const EdgeInsets.symmetric(
                    horizontal: 18, vertical: 12),
              ),
              onSubmitted: (_) => _sendMessage(),
            ),
          ),
          const SizedBox(width: 10),
          AnimatedContainer(
            duration: const Duration(milliseconds: 200),
            child: Material(
              color: _isTyping
                  ? AppTheme.surfaceLight
                  : AppTheme.accent,
              borderRadius: BorderRadius.circular(20),
              child: InkWell(
                onTap: _isTyping ? null : _sendMessage,
                borderRadius: BorderRadius.circular(20),
                child: Container(
                  width: 48,
                  height: 48,
                  alignment: Alignment.center,
                  child: _isTyping
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: AppTheme.textSecondary,
                          ),
                        )
                      : const Icon(Icons.send_rounded,
                          color: Colors.white, size: 20),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────
// MESSAGE BUBBLE
// ─────────────────────────────────────────────────────────────

class _MessageBubble extends StatelessWidget {
  final MessageModel message;

  const _MessageBubble({required this.message});

  @override
  Widget build(BuildContext context) {
    final isUser = message.isUser;
    final emotionColor = EmotionDetector.getEmotionColor(message.emotion);
    final timeStr = DateFormat('HH:mm').format(message.timestamp);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        mainAxisAlignment:
            isUser ? MainAxisAlignment.end : MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          if (!isUser) ...[
            // AI Avatar
            Container(
              width: 32,
              height: 32,
              margin: const EdgeInsets.only(right: 8),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [AppTheme.accent, AppTheme.accentWarm],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(Icons.favorite_rounded,
                  color: Colors.white, size: 16),
            ),
          ],
          // Bubble
          Flexible(
            child: Column(
              crossAxisAlignment: isUser
                  ? CrossAxisAlignment.end
                  : CrossAxisAlignment.start,
              children: [
                Container(
                  constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.72,
                  ),
                  padding: const EdgeInsets.symmetric(
                      horizontal: 16, vertical: 12),
                  decoration: BoxDecoration(
                    color: isUser ? AppTheme.userBubble : AppTheme.aiBubble,
                    borderRadius: BorderRadius.only(
                      topLeft: const Radius.circular(18),
                      topRight: const Radius.circular(18),
                      bottomLeft: Radius.circular(isUser ? 18 : 4),
                      bottomRight: Radius.circular(isUser ? 4 : 18),
                    ),
                    border: isUser
                        ? null
                        : Border.all(
                            color: AppTheme.divider,
                            width: 1,
                          ),
                  ),
                  child: Text(
                    message.content,
                    style: GoogleFonts.dmSans(
                      color: AppTheme.textPrimary,
                      fontSize: 15,
                      height: 1.5,
                    ),
                  ),
                ),
                const SizedBox(height: 4),
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (isUser && message.emotion != 'neutral') ...[
                      Text(
                        EmotionDetector.getEmotionEmoji(message.emotion),
                        style: const TextStyle(fontSize: 12),
                      ),
                      const SizedBox(width: 4),
                      Text(
                        message.emotion,
                        style: GoogleFonts.dmSans(
                          color: emotionColor.withOpacity(0.8),
                          fontSize: 11,
                        ),
                      ),
                      const SizedBox(width: 6),
                    ],
                    Text(
                      timeStr,
                      style: GoogleFonts.dmSans(
                        color: AppTheme.textSecondary,
                        fontSize: 11,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          if (isUser) const SizedBox(width: 4),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────
// TYPING INDICATOR
// ─────────────────────────────────────────────────────────────

class _TypingIndicator extends StatelessWidget {
  final Animation<double> animation;

  const _TypingIndicator({required this.animation});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        children: [
          Container(
            width: 32,
            height: 32,
            margin: const EdgeInsets.only(right: 8),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [AppTheme.accent, AppTheme.accentWarm],
              ),
              borderRadius: BorderRadius.circular(10),
            ),
            child: const Icon(Icons.favorite_rounded,
                color: Colors.white, size: 16),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            decoration: BoxDecoration(
              color: AppTheme.aiBubble,
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(18),
                topRight: Radius.circular(18),
                bottomRight: Radius.circular(18),
                bottomLeft: Radius.circular(4),
              ),
              border: Border.all(color: AppTheme.divider),
            ),
            child: Row(
              children: List.generate(3, (i) {
                return AnimatedBuilder(
                  animation: animation,
                  builder: (_, __) {
                    return Container(
                      margin: EdgeInsets.only(right: i < 2 ? 4 : 0),
                      width: 8,
                      height: 8,
                      decoration: BoxDecoration(
                        color: AppTheme.textSecondary.withOpacity(
                          (animation.value + i * 0.2).clamp(0.2, 1.0),
                        ),
                        shape: BoxShape.circle,
                      ),
                    );
                  },
                );
              }),
            ),
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────
// HELPER WIDGETS
// ─────────────────────────────────────────────────────────────

class _EmotionBadge extends StatelessWidget {
  final String emotion;
  final double confidence;

  const _EmotionBadge({required this.emotion, required this.confidence});

  @override
  Widget build(BuildContext context) {
    final color = EmotionDetector.getEmotionColor(emotion);
    final emoji = EmotionDetector.getEmotionEmoji(emotion);

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: color.withOpacity(0.15),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(emoji, style: const TextStyle(fontSize: 12)),
          const SizedBox(width: 4),
          Text(
            emotion,
            style: GoogleFonts.dmSans(
              color: color,
              fontSize: 12,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }
}

class _StatsChip extends StatelessWidget {
  final int count;
  final String label;

  const _StatsChip({required this.count, required this.label});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: AppTheme.surfaceLight,
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        '$count $label',
        style: GoogleFonts.dmSans(
          color: AppTheme.textSecondary,
          fontSize: 12,
        ),
      ),
    );
  }
}

class _SuggestionChip extends StatelessWidget {
  final String text;
  final VoidCallback onTap;

  const _SuggestionChip({required this.text, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return Material(
      color: AppTheme.surfaceLight,
      borderRadius: BorderRadius.circular(20),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(20),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20),
            border: Border.all(color: AppTheme.divider),
          ),
          child: Text(
            text,
            style: GoogleFonts.dmSans(
              color: AppTheme.textSecondary,
              fontSize: 13,
            ),
          ),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────
// NOTE: The file main.g.dart is auto-generated by build_runner
// Run: dart run build_runner build
// It generates MessageModelAdapter and ConversationModelAdapter
// ─────────────────────────────────────────────────────────────
